<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 16.03.2018
 * Time: 09:27
 */

namespace AppBundle\Controller;

use AppBundle\Entity\Contacts;
use AppBundle\Form\ContactType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;


class MyContactsController extends Controller
{
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    public function contactsAction()
    {
        $entityManager = $this->getDoctrine()->getManager();
        $contacts = $entityManager->getRepository(Contacts::class)->findBy(["owner"=>$this->getUser()]);

        return $this->render("MyContacts/contacts.html.twig", ['contacts'=>$contacts]);
    }

    public function detailsAction(Contacts $contact)
    {
        return $this->render('MyContacts/details.html.twig',['contact'=>$contact]);
    }

    public function addAction(Request $request)
    {
        $contact = new Contacts();
        $form = $this->createForm(ContactType::class, $contact);

        if($request->isMethod('post'))
        {
            $form->handleRequest($request);

            if($form->isValid()) {
                if ($contact->getPicture() != null) {
                    $file = $contact->getPicture();
                    $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

                    $file->move(
                        $this->getParameter('profile_directory'),
                        $fileName
                    );

                    $contact->setPicture($fileName);
                }
                $contact->setOwner($this->getUser());
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($contact);
                $entityManager->flush();

                $this->addFlash("success", "Contact {$contact->getName()} has been successfully added");

                return $this->redirectToRoute('contacts_details',['id'=>$contact->getId()]);
            }
            $this->addFlash("error","Add Failed");
        }

        return $this->render('MyContacts/add.html.twig',['form'=>$form->createView()]);

    }

}