app:
    resource: '@AppBundle/Controller/'
    type: annotation

contacts_index:
  path: /
  defaults: {_controller: AppBundle:Contacts:index}
  methods:  [GET]

contacts_details:
  path: /contacts/details/{id}
  defaults: {_controller: AppBundle:Contacts:details}
  methods: [GET]