app:
    resource: '@AppBundle/Controller/'
    type: annotation

contacts_index:
  path: /
  defaults: {_controller: AppBundle:Contacts:index}
  methods:  [GET]

contacts_details:
  path: /contacts/details/{id}
  defaults: {_controller: AppBundle:Contacts:details}
  methods: [GET]



my_contacts_contacts:
  path: /MyContacts
  defaults: {_controller: AppBundle:MyContacts:contacts}
  methods:  [GET]

my_contacts_add:
  path: /MyContacts/add
  defaults: {_controller: AppBundle:MyContacts:add}
  methods:  [GET,POST]

my_contacts_details:
  path: /MyContacts/details/{id}
  defaults: {_controller: AppBundle:MyContacts:details}
  methods: [GET]



fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile