
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
                    pattern: ^/
                    form_login:
                        provider: fos_userbundle
                        csrf_token_generator: security.csrf.token_manager
                        login_path: fos_user_security_login
                        use_forward: false
                        check_path: fos_user_security_check
                        failure_path:  fos_user_security_login
                        always_use_default_target_path: false
                        default_target_path: contacts_index
                        target_path_parameter: _target_path
                        use_referer: true
                        remember_me: true
                    anonymous:    true
                    logout:
                        path: fos_user_security_logout
                        target: contacts_index
                    remember_me:
                        secret: "%secret%"
                        lifetime: 43200 # 12 hours
                        path: /
                        domain: localhost # TODO

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }